### ISSUE TITLE
Progressbar is gone after starting the print

### ISSUE THREAD

**Issue by NilsRo** [sethvoltz/OctoPrint-DisplayPanel#51]
Hi.

After starting the print the progressbar is gone with new version 2.0. It seems to be related to the estimation of the remaining time. If it is not calculated yet in OctoPrint Webfrontend the progressbar is not visible. As it is visible before the print starts it should stay on 0% or should be invisible also on the print start.

![image](https://user-images.githubusercontent.com/51311453/107121327-18788e80-6892-11eb-973e-92d805f4e1a1.jpeg)

Regards,
Nils

**Comment by unclej84** [comment]
Hello @NilsRo,

this is really strange. Is it missing on all screens? What settings do you use (Rotation, Progress on Top....)? Was it still heating up at this point or already printing? Are you using any special plugins?

**Comment by NilsRo** [comment]
Hi. 

Everything is set to standard as I updated to V2 Plug-in and changed the display format of the end time only. The bar is only gone during heat up. Before and after it is visible. There is no special plug-in that changing this information but I plan to use one to better calculate the remaining time. But not important here.

**Comment by unclej84** [comment]
Is there any output from the plugin in octoprint.log?

**Comment by NilsRo** [comment]
Nothing in the log. But I did not enable a debuglevel or something else.

**Comment by NilsRo** [comment]
Hi,

I setup a dev environment to develop my own plugin and found this during virtual printing. So it seems matching the issue on my real OctoPrint perhaps. Seems to be a tpe mismatch.

alueError: could not convert string to float: '-'
2021-02-20 14:51:25,821 - octoprint.plugins.display_panel - WARNING - An exception of type TypeError occurred on log_error. Arguments: ("argument of type 'NoneType' is not iterable",)
2021-02-20 14:51:25,821 - octoprint.plugins.display_panel - WARNING - An exception of type TypeError occurred on log_error. Arguments: ("unsupported operand type(s) for +: 'int' and 'NoneType'",)
2021-02-20 14:51:25,926 - octoprint.plugin - ERROR - Error while calling plugin display_panel
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugin/__init__.py", line 271, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1890, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_display_panel/__init__.py", line 159, in on_event
    self._displaylayerprogress_total_height = float(payload.get('totalHeight'))
ValueError: could not convert string to float: '-'
2021-02-20 14:51:26,149 - octoprint.plugin - ERROR - Error while calling plugin display_panel
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugin/__init__.py", line 271, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1890, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_display_panel/__init__.py", line 159, in on_event
    self._displaylayerprogress_total_height = float(payload.get('totalHeight'))
ValueError: could not convert string to float: '-'
2021-02-20 14:51:26,173 - octoprint.plugins.display_panel - WARNING - An exception of type TypeError occurred on log_error. Arguments: ("argument of type 'NoneType' is not iterable",)
2021-02-20 14:51:26,174 - octoprint.plugins.display_panel - WARNING - An exception of type TypeError occurred on log_error. Arguments: ("unsupported operand type(s) for +: 'int' and 'NoneType'",)
2021-02-20 14:51:26,288 - octoprint.plugin - ERROR - Error while calling plugin display_panel
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugin/__init__.py", line 271, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1890, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_display_panel/__init__.py", line 159, in on_event
    self._displaylayerprogress_total_height = float(payload.get('totalHeight'))
ValueError: could not convert string to float: '-'

**Comment by sethvoltz** [comment]
I just pushed up v2.1.0, can you test again after you upgrade? I think I may not have included some safety code around this in the earlier releases. If it persists, I'll take another look into this.

Thanks!

**Comment by sethvoltz** [comment]
Also, I dig the color and placement of your build. You should post a picture in the [Case Design Show and Tell](https://github.com/sethvoltz/OctoPrint-DisplayPanel/discussions/32)

**Comment by NilsRo** [comment]
Hi. There error is still there. It happens in the case no estimation is available. The GUI looks like this and there are also Typ Conversion errors in the log. In my opinion check is missing if the estimation is "None".  

![grafik](https://user-images.githubusercontent.com/51311453/109540684-1dacb000-7ac3-11eb-8c8d-04a3695a3cfa.png)
![grafik](https://user-images.githubusercontent.com/51311453/109540719-27361800-7ac3-11eb-9769-407cb6e4ac99.png)

**Comment by sethvoltz** [comment]
Whoops, didn't want this to get closed. Bad robot. @NilsRo been super busy at work but this is still on my radar to dig into

**Comment by NilsRo** [comment]
I now get the following error continuously during print. But the bar is visible. Still updated to newest V3.

2021-05-07 01:46:10,335 - octoprint.plugins.display_panel - WARNING - An exception of type TypeError occurred on log_error. Arguments: ("argument of type 'NoneType' is not iterable",)

**Comment by NilsRo** [comment]
Hi,

progressbar is there now but the exception is still there and producing much errors in the log. Do you have an idea how to solve this?

Cheers,
Nils
[octoprint(2).log](https://github.com/sethvoltz/OctoPrint-DisplayPanel/files/6750520/octoprint.2.log)
